# Generated by Django 4.2 on 2023-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('1', 'personal_chat'), ('2', 'group_chat'), ('3', 'group_private_chat')], max_length=2),
        ),
    ]
